# Generated by Django 4.2.13 on 2024-06-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concert", "0002_concert_city_concert_concert_name_concert_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="city",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="concert",
            name="concert_name",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="concert",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
